### PR TITLE
Allow all ascii chars in sender/receiver local part of mail address

### PR DESCRIPTION
**Pull request by danBLA**
- before only one '@' was allowed in whole mail address
- but "a@b"@c is legitimate (local part has to be in quotes)
- we don't check for "" around the local part if finding special chars since we assume these invalid addresses would be dectected before fuglu

### CODE REVIEW

**Comment by gryphius** [comment]
iirc we were too strict on purpose. Even if RFC might allow for "a@b"@c do you see a legitimate usecase to accept this? If so, maybe we should make this configurable?

**Comment by danBLA** [comment]
True. There's no common use case, maybe some sort of SRS.
But I think accepting/rejecting mail addresses should happen before fuglu receives the mail.

**Comment by gryphius** [comment]
> But I think accepting/rejecting mail addresses should happen before fuglu receives the mail

That is generally true, but if we agree that there are cases like this where a sender address is obviously broken but still RFC compliant then I'd rather have fuglu bail out by default instead of having to reconfigure every postfix instance. If your MTA had rejected such addresses you'd not be patching this ;-)

**Comment by jahlives** [comment]
reject such message by fuglu is okay on a mx if running in prequeue/milter mode but imho not for a scanner behind the mx. In this case fuglu cannot process something that mta (actually two mta in our case) accepted and this will stuck in q. After qlifetime we have to bounce back to this crappy sender :-)

**Comment by gryphius** [comment]
True... Which means we should 5xx adresses we don't like instead of treating this as a 4xx

**Comment by jahlives** [comment]
5xx solves the q problem but still a bounce must be sent to sender. And we can almost certain be sure that a sender with two @ is a spam/fake/malware/crap not worth even consider to send a bounce :-)
Best approach imho is: trust mta and accpet anything that mta passes to fuglu. As it comes from mta we can be quite sure that this mta will accept the re-inject by fuglu with that envelope sender/rcpt

**Comment by jahlives** [comment]
@gyryphius
Would be nice to be able to config the behaviour like you suggested.
On the result to mta it might be good to make it configurable too: like return 4xx or 5xx or store it /dev/null :-)

**Comment by danBLA** [comment]
May I suggest two new config inputs:
- `address_compliance_checker` which takes a class name checking the address. Some classes might be built-in but it can be extended as it is allowed for plugins
   - `DefaultAddrCheck` implements functionality as it is currently in the repo
   - `PermissiveAddrCheck` Which is the implementation of this PR
- `address_compliance_return_code` which takes an integer as failed return code

> There are several examples of code which wrongfully does something like someaddress.split('@',1) instead of .rsplit('@',1) This will choke with such addresses

Btw, I think the internally most consistent implementation for splitting envelope from/to addresses are the functions available from suspect which are also tested:
```   def test_from_to_local_addr(self):
        """Make sure local senders / recipients are accepted"""
        s = Suspect('bob@localhost', 'root@localhost', '/dev/null')
        self.assertEqual("bob@localhost", s.from_address)
        self.assertEqual("bob", s.from_localpart)
        self.assertEqual("localhost", s.from_domain)

        self.assertEqual("root@localhost", s.to_address)
        self.assertEqual("root", s.to_localpart)
        self.assertEqual("localhost", s.to_domain)
```

**Comment by danBLA** [comment]
Now latest pull request has the inputs to configure the mail checker (fuglu.conf):

```
# Method to check mail address validity (Default/LazyLocalPart)
address_compliance_checker = Default

# Action to perform if address validity check fails (defer/reject/discard)
address_compliance_fail_action = defer

# Reply message if address validity check fails
address_compliance_fail_message = invalid send or receive address
```

And also an additional input to fix #162 
```
# Remove temporary message file from disk for receive or address compliance errors
remove_tmpfiles_on_error = True
```

**Pull request merged**
